name: GitHub Actions Demo
on:
  repository_dispatch:
    types: [update-tokens]
    branches:
      - main
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'information'
        type: choice
        options:
          - information
          - debug
          - warning
          - critical
      tags:
        description: 'Purpose of Run This Workflow?'
        required: true
        type: string

jobs:
  jobs:
  update-ui-kit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configurar credenciales de Git
      run: |
        git config --global user.email jsainz@veridas.com
        git config --global user.name jsainz

    - name: Commit UI Kit updates
      run: |
        git add .
        git commit -m "${{github.event.client_payload.commitMessage}}"
        git diff --quiet || git push