name: GitHub Actions Demo
on:
  repository_dispatch:
    types: [update-tokens]
    branches:
      - main
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'information'
        type: choice
        options:
          - information
          - debug
          - warning
          - critical
      tags:
        description: 'Purpose of Run This Workflow?'
        required: true
        type: string

jobs:
  generate-and-commit-files:
    runs-on: ubuntu-latest
    steps:
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: jsainz
          author_email: jsainz@veridas.com
          message: '${{github.event.client_payload.filename}}'
          add: '*.json'
      
