name: GitHub Actions Demo
on:
  repository_dispatch:
    types: [update-tokens]
    branches:
      - main
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'information'
        type: choice
        options:
          - information
          - debug
          - warning
          - critical
      tags:
        description: 'Purpose of Run This Workflow?'
        required: true
        type: string

jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Print the purpose of run
        run: echo  ${{github.event.client_payload.filename}}
    script:
      git add -A
      git commit -m "${{github.event.client_payload.commitMessage}}"
      git push --set-upstream origin master 
