name: GitHub Actions Demo
on:
  repository_dispatch:
    types: [update-tokens]
    branches:
      - main
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'information'
        type: choice
        options:
          - information
          - debug
          - warning
          - critical
      tags:
        description: 'Purpose of Run This Workflow?'
        required: true
        type: string

jobs:
  generate-and-commit-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/head
          fetch-depth: 0
      - uses: jsainz-veridas/design-tokens@main
        with:
          commit_message: ${{github.event.client_payload.filename}}
