name: GitHub Actions Demo
on:
  repository_dispatch:
    types: [update-tokens]
    branches:
      - main
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'information'
        type: choice
        options:
          - information
          - debug
          - warning
          - critical
      tags:
        description: 'Purpose of Run This Workflow?'
        required: true
        type: string

jobs:
  json_content: |
    ${{github.event.client_payload.tokens}}
  update-ui-kit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Configurar credenciales de Git
        run: |
          git config --global user.email "jsainz@veridas.com"
          git config --global user.name "jsainz"

      - name: Actualizar cambios
        run: |
          git add $json_data
          git commit -m '${{github.event.client_payload.commitMessage}}''
          git push