name: GitHub Actions Demo
on:
  repository_dispatch:
    types: [update-tokens]
    branches:
      - main
jobs:
  update-ui-kit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Configurar credenciales de Git
        run: |
          git config --global user.email "jsainz@veridas.com"
          git config --global user.name "jsainz"
      - name: Make changes to files
        run: |
          echo '${{github.event.client_payload.tokens}}' > ${{ github.event.client_payload.filename }}
      - name: Actualizar cambios
        run: |
          git add .
          git commit -m '${{github.event.client_payload.commitMessage}}'
          git push