name: GitHub Actions Demo
on:
  repository_dispatch:
    types: [update-tokens]
    branches:
      - main
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'information'
        type: choice
        options:
          - information
          - debug
          - warning
          - critical
      tags:
        description: 'Purpose of Run This Workflow?'
        required: true
        type: string

jobs:
  generate-and-commit-files:
    runs-on: ubuntu-latest
    steps:
      - name: Print the purpose of run

      - uses: jsainz-veridas/git-auto-commit-action@v4
        with:
          commit_message: ${{github.event.client_payload.filename}}
